baseurl = " https://khadeerds.github.io/DataEngineer"
# Title of your site
title = "Khadeer Data Engineer"
theme = "hugo-coder"
DefaultContentLanguage = "en"
defaultcontentlanguage = "en"
publishDir="docs"
paginate = 20 # Number of items per page in paginated lists.
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
hasCJKLanguage = true # Set `true` for Chinese/Japanese/Korean languages.
pygmentscodefencesguesssyntax = true
#disqusShortname = "yourdiscussshortname"
defaultContentLanguageInSubdir = false
removePathAccents = true # Workaround for https://github.com/gohugoio/hugo/issues/5687

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; Khadeer Bava, {year}"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = "khadeer"

# Get last modified date for content from Git?
enableGitInfo = false

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[params]
    author = "Khadeer Bava Shaik"
    description = "Khadeer personal website"
    keywords = "Data Engineer ,BigData developer,Bi Analytics"
    info = "Big-Data Management and Analytics"
    avatarurl = "images/pic3.JPG"
    footercontent = "**Success usually comes to those who are too busy to be looking for it**"
    dateformat = "January 2, 2006"
    hideCredits = true
    hideCopyright = true
    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"
    rtl = false
    #Specify light/dark colorscheme
    #Supported values:
    #"auto" (use preference set by browser)
    #"dark" (dark background, light foreground)
    #"light" (light background, dark foreground) (default)
    colorscheme = "dark"
    # Series see also post count
    maxSeeAlsoItems = 10
    # Custom CSS
    custom_css = []
    # Custom JS
    custom_js = []
[taxonomies]
  publication_type = "publication_types"
  author = "authors"
  category = "categories"
  series = "series"
  tag = "tags"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/KHADEERDS/"
[[params.social]]
    name = "Facebook"
    icon_pack = "ai"
    weight = 2
    url = "https://www.facebook.com/khadeer.king/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/khadeer99/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/khadeer-s-5a159062/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@khadeer5599/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "/about/"

            [[languages.en.menu.main]]
            name = "Tutorials"
            weight = 2
            url = "/Tutorials/"
			
			[[languages.en.menu.main]]
            name = "PySpark"
            weight = 2
            url = "/PySpark_Tutorial/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "/projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "/contact/"


# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.
